### ISSUE TITLE
[Vis] Visualize model performance

### ISSUE THREAD

**Issue by c-schicho** [c-schicho/AOS-ImageRestoration#10]
Implement a function that saves performance of past training runs. 

Implement a function that visualizes and compares performance of different architectures networks.

**Comment by Xenonblues** [comment]
"saves performance": write metrics (SSIM, MSE, PSNR) to a file that can be saved and loaded afterwards? Metrics are already calculated at that point?
"visualizes": comparison via bar graph of different ML approaches

**Comment by c-schicho** [comment]
https://github.com/j3soon/tbparse might be helpful to load the tb data into a dataframe
