### ISSUE TITLE
[Training] Train the baseline

### ISSUE THREAD

**Issue by SchmidtPhilipp** [c-schicho/AOS-ImageRestoration#14]

**Comment by c-schicho** [comment]
results can be found in this folder https://drive.google.com/drive/folders/1N_xlWS6XQQshAVO7AhhGW1DXYBnAIaU8

hyperparameters have been the default values except for the ones below.

command was `python3 main.py --train True --data_name focalstack-1 --save_each_model True --workers 2 --seed 1234`
